// Корневой build.gradle для монорепозитория
plugins {
    id 'base'
    id 'co.uzzu.dotenv.gradle' version '4.0.0'
}

allprojects {
    group = 'com.launcher'
    version = '0.0.3'
    
    repositories {
        mavenCentral()
        if (project.path.startsWith(':mods:')) {
            maven { url 'https://maven.fabricmc.net/' }
        }
    }
}