pluginManagement {
    repositories {
        maven { url 'https://maven.fabricmc.net/' }
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = 'launcher-monorepo'

include 'backend'
include 'mods:launcher_auth'
include 'mods:launcher_auto_connect'
include 'mods:no_creepers_phantoms'
include 'mods:debug_op_only'
include 'mods:nochatlag'
