// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AuthGetSession():Promise<main.AuthSession>;

export function AuthIsAuthenticated():Promise<boolean>;

export function AuthLogout():Promise<void>;

export function AuthRefreshSession():Promise<main.AuthSession>;

export function AuthStartLogin():Promise<main.AuthSession>;

export function GetConfig():Promise<main.Config>;

export function GetNewsFeed():Promise<main.NewsFeedResponse>;

export function Greet(arg1:string):Promise<string>;

export function PlayMinecraft():Promise<void>;

export function SaveConfig(arg1:main.Config):Promise<void>;
