// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthGetSession() {
  return window['go']['main']['App']['AuthGetSession']();
}

export function AuthIsAuthenticated() {
  return window['go']['main']['App']['AuthIsAuthenticated']();
}

export function AuthLogout() {
  return window['go']['main']['App']['AuthLogout']();
}

export function AuthRefreshSession() {
  return window['go']['main']['App']['AuthRefreshSession']();
}

export function AuthStartLogin() {
  return window['go']['main']['App']['AuthStartLogin']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetNewsFeed() {
  return window['go']['main']['App']['GetNewsFeed']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function PlayMinecraft() {
  return window['go']['main']['App']['PlayMinecraft']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}
