Args = --initialize-at-run-time=sun.awt \
       --initialize-at-run-time=java.awt \
       --initialize-at-run-time=javax.swing \
       --initialize-at-run-time=sun.java2d \
       --initialize-at-run-time=sun.font \
       --initialize-at-run-time=sun.lwawt \
       --initialize-at-run-time=java.awt.Toolkit \
       --initialize-at-run-time=java.awt.GraphicsEnvironment \
       --initialize-at-run-time=sun.awt.windows \
       --initialize-at-run-time=sun.java2d.windows \
       -H:+JNI \
       -H:JNIConfigurationResources=META-INF/native-image/jni-config.json
